dataconfig:
  db-url: jdbc:oracle:thin:@localhost:1521:xe
  db-username: user01
  db-password: 1234
  google-mail-url: dragonyxit@gmail.com
  google-mail-password: tepmacdqorgmlbfx
  rememberme-key: hayden